---
title: Real-time Perceptions of Financial Market Stress
author: Christopher Gandrud, Sahil Deo, Christian Franz, and Mark Hallerberg
output:
    pdf_document:
        keep_tex: yes
bibliography: main.bib
linestretch: 1.5
---

**Note: This work is in the early stages of development. It will be updated significantly.**

**Abstract**[^ThankYou]

> This paper describes the motivation and construction of a new measure of
real-time perceptions of financial market stress based on machine classification of
[Economist Intelligence Unit](http://www.eiu.com/) monthly country reports.

Why and how do politicians respond to financial market stress? This question has attracted considerable attention recently following the 2007-2009 financial crisis and earlier following the late-1990s Asian financial crisis. However, virtually all of this research lacks a crucial variable: a real-time indication of the level of financial market stress that policy-makers believed that they faced. To understand why politicians made a given policy choice, we need to have a measure of what problems they faced.

Most research has used *post-hoc* assessments of banking crisis as a second-best alternative. However, this presents clear problems. Chiefly, using such measures creates clear selection bias as stress that politicians responded to effectively will not be selected. In addition, these measures are typically binary and so give now indication of stress intensity. The measures are also at gross intervals, typically yearly, prohibiting sub-annual analysis.

In this paper we aim to overcome these problems by develop a new index of real-time perceptions of financial market stress. The index is created using a kernel principal component analysis of monthly Economist Intelligence Unit (EIU) reports. This measure should supplant previous second-best measures of financial market stress by researchers aiming to understand why and how policy-makers respond to financial crisis.

We start the paper by detailing our motivation for creating a real-time index of perceptions of financial market stress. We then discuss the construction of the Index and compare it to widely used previous measures of financial market stress. [WOULD BE NICE TO HAVE A REPLICATION OF AN IMPORTANT PAPER].

## Motivation

Researchers have tended to rely on two data sources for cross-country information on when a country is facing a financial crisis: @laeven2013 and @Reinhart2009. Knowing when crises started (and when they have ended) is crucial for research trying to understand issues such as how crises affect economic output, how governments choose to respond to financial market distress, and what the fiscal costs of financial crises are.

There are a number of problems with these indicators. Unlike economic recessions, financial crises are poorly defined in previous sources. This contributes to large inconsistencies between the timing of crises in the @laeven2013 and @Reinhart2009 data sets [@Chaudron2014]. For example, Japan is labeled as having a crisis between 1997 and 2001 by the former, but 1992-1997 in the latter. @GandrudHallerberg2015 also find that there are significant difference in crisis timing between different versions of the @laeven2013 data. Crises are also identified by researchers who know what happened. Financial market stress that is addressed well by policymakers, preventing a major crisis, may therefore not be included. Similarly, stress that is temporarily dampened through unsustainable policy measures, only to flare up later, is not clearly recorded. This makes it difficult to adequately study why and how politicians respond to financial market stress. Related to this, current measures are dichotomous thus errors have large consequences for creating bias when used in econometric models. They also do not give any indication of how severe a crisis is.

Overall, we lack the continuous real-time measure of financial market stress that we need to be able to adequately examine why and how policy-makers respond to financial market problems.

There have been a number of recent attempts to create crisis measures that overcome these issues. Building on @vonHagen2007, @Jing2015 developed am index of money market pressure based on changes in short-term interest rates and stocks of central bank reserves. However, this measure conflates distress and policy responses, assuming central banks use the same reaction function to increased demand for liquidity. @Rosas2009 developed a dynamic latent trait model of banking system distress. However, his measure relies on nationally reported data to the IMF's International Financial Statistics, which @GandrudCopHal2015 show can be endogenous to financial market distress.

@Romer2014 aimed to address this issue by manually classifying 24 countries on a 15 point scale capturing the cost of credit intermediation. They code countries using information from OECD semi-annual *Economic Outlook* reports from 1967 to 2007. Relying on contemporaneous reports allows for the construction of a real-time measure of credit market distress. This would allow us to examine policy choices that head off trouble or unsustainably prolong brewing difficulties. Their, relatively, continuous measure gives an indication of market distress intensity.

Their approach could be improved in a number of key ways. First, they are necessarily limited to the relatively small sample of OECD countries. Second, their measure is laborious to create and update. Third, the scale is created by simply summing

[COMPLETE]

## Creating the Perceptions of Financial Market Stress Index

We propose a new method of estimating a real-time measure of perceptions of financial market stress. The index is created with kernel principle component analysis [@Scholkopf1998; @Spirling2012] of monthly country reports from the **Economist Intelligence Unit**.[^EIU]

### Why the EIU?

The EIU is the product of a an analysis of real-time, third-party assessments of financial market conditions reported monthly. These reports are both a summary of real-time information on counties' economic conditions as well as a a channel through which this information is disseminated. Together, the reports create a very large corpus (more than 20,000 texts from 1997 through 2011 [CHECK]) of monthly reports for more than 100 countries. As the texts generally follow the same format and style, they contain directly comparable assessments of economic conditions monthly across the globe for a significant time span. In contrast, the OECD **Economic Outlook** provides comparable reports for a very small number of wealthy countries on a bi-annual basis.

### Summarising the EUI

Our aim is to create an index that classifies financial conditions on a continuous more-stressed/less stressed spectrum. So we clearly need an efficient way to summarize the vast quantity of information in the EIU reports. To do this we proceeded in the following steps. We collected the parsed reports--the reports were in HTML format. We then extracted the portions of the texts--headlines and paragraphs--that contained at least one of a number of keywords.[^keywords]

Due to a significant change in how the reports were constructed in 2003, we also selected only texts from 2003 in order to maintain comparability.

#### Text selection

EIU reports contain assessments of a wide range of countries' economies, not just their financial system. So, our first step was to select the portions of the EIU texts that contained relevant information about countries' banking and financial systems.


#### Kernel Principal Component Analysis




#### Data subsetting

## Comparison to Other Crisis Measures

## Conclusions and Possible Future Work

## References


[^ThankYou]: Thank you to Ronen Palan for helpful comments.

[^EIU]: See <http://www.eiu.com/>. Accessed May 2015.

[^keywords]: The keywords included: *bail-out*, *bailout*, *balance sheet*, *bank*, *credit*,
              *crunch*, *default*, *financial*, *lend*, *loan*, *squeeze* [MAKE SURE TO UPDATE]. These keywords were adapted from those used by @Romer2014 and are intended to select passages that discusses credit market conditions.  
